#base	"../../../customizations/resolutions/4x3/backpackpanel.res"
#base	"../../../customizations/resolutions/5x4/backpackpanel.res"
#base	"../../../customizations/resolutions/16x10/backpackpanel.res"
#base	"../../../customizations/resolutions/16x9/backpackpanel.res"
#base	"backpackpanel_base.res"