#base	"../../customizations/resolutions/4x3/charinfoloadoutsubpanel.res"
#base	"../../customizations/resolutions/5x4/charinfoloadoutsubpanel.res"
#base	"../../customizations/resolutions/16x10/charinfoloadoutsubpanel.res"
#base	"../../customizations/resolutions/16x9/charinfoloadoutsubpanel.res"
#base	"charinfoloadoutsubpanel_base.res"