#base	"../../customizations/resolutions/4x3/classloadoutpanel.res"
#base	"../../customizations/resolutions/5x4/classloadoutpanel.res"
#base	"../../customizations/resolutions/16x10/classloadoutpanel.res"
#base	"../../customizations/resolutions/16x9/classloadoutpanel.res"
#base	"classloadoutpanel_base.res"