#base	"../../customizations/resolutions/4x3/mainmenuplaylistentry.res"
#base	"../../customizations/resolutions/5x4/mainmenuplaylistentry.res"
#base	"../../customizations/resolutions/16x10/mainmenuplaylistentry.res"
#base	"../../customizations/resolutions/16x9/mainmenuplaylistentry.res"
#base 	"mainmenuplaylistentry_base.res"