#base	"../../customizations/resolutions/4x3/matchmakingplaylist.res"
#base	"../../customizations/resolutions/5x4/matchmakingplaylist.res"
#base	"../../customizations/resolutions/16x10/matchmakingplaylist.res"
#base	"../../customizations/resolutions/16x9/matchmakingplaylist.res"
#base 	"matchmakingplaylist_base.res"